In [14]:
a1 = [ 3,2,6]
a1 * 2

d1 = {'k1':3, 'k2':2, 'k3':6}

a1[0]  #indexing
a1[1:3] #slicing

#a2라는 리스트, 4,7,'a', a1, 5
#a2의 4번째 값
#a2의 1~3번째 값

a2 = [4,7, 'a', a1, 5]
a2[  3 ]
a2[  :3   ]

[4, 7, 'a']

In [16]:
if  a2[0] >2  :
  print("ok")
elif a2[0] <= 2:
  print("no1")
else:
  print("no")

#indentation

ok


In [22]:
a3 = []

for  i  in  a1 :
  if i > 2:
    a3.append(i*2)

a4 = [i*2 for  i  in  a1 if i > 2  ]
a4

[6, 12]

In [25]:
import numpy as np

a5 = np.array( a1 )
a5 * 2


array([ 6,  4, 12])

In [27]:
from numpy import array
array( a1 )* 2

array([ 6,  4, 12])

In [35]:
a6 = [ [3,2],
      [6,5],
       [4,1]]
a7 = np.array( a6 )
a7[ 0 , 0 ]
a7[ 1, 0:2 ]
a7[ 1, : ]
#a7 2열의 1-2행
a7[  0:2  ,  1 ]


array([2, 5])

In [ ]:
import pandas as pd
#creditset2.csv를 업로드 -> 아래 라인 실행
df1 = pd.read_csv("creditset2.csv")
df1.index #행이름
df1.columns #열이름
df1.values #array로 표현된 실제값

#adv.csv를 읽으셔서 df2
#df2의 values를 출력하셔서 10-15행, 2-3열
df2 =  pd.read_csv("adv.csv")
df2.values[9:15   , 1:3   ]

In [59]:
#df2.info()
df2.TV
df2["TV"]

#df2 TV, radio 두 컬럼의 차이 계산
df2.TV - df2.radio

#sp500_tm.csv를 읽으셔서 df3
#info()
#direction컬럼선택해서 출력해보세요

df3 = pd.read_csv("sp500_tm.csv")
#df3.info()
df3.Direction
df3.head()
df3.Direction.unique()
df3.Direction.value_counts()
df3["new1"] = df3.avgPos > df3.avgNeg   #컬럼 추가
df3.head()
df3.to_csv("new.csv")

In [60]:
#weatherAUS.csv를 df4로 읽으세요
#info()를 수행해서 컬럼 및 null값 여부를 파악해보세요
#RainTomorrow에 대해서 value_counts를 적용해보세요
#RainToday와 RainTomorrow가 같은지 비교해보고 새로운 컬럼으로 만드세요
#데이터프레임을 new2.csv로 저장해보세요.

#creditset2.csv를 읽은 df1에서 default10yr에 대해 value counts를 적용해보세요
#loan을 income 컬럼으로 나눈 결과와 LTI 컬럼을 비교해보세요

income        age         loan  default10yr
0     66155.92510  59.017015  8106.532131            0
1     34415.15397  48.117153  6564.745018            0
2     57317.17006  63.108049  8020.953296            0
3     42709.53420  45.751972  6103.642260            0
4     66952.68885  18.584336  8770.099235            1
...           ...        ...          ...          ...
1995  59221.04487  48.518179  1926.729397            0
1996  69516.12757  23.162104  3503.176156            0
1997  44311.44926  28.017167  5522.786693            1
1998  43756.05660  63.971796  1622.722598            0
1999  69436.57955  56.152617  7378.833599            0

[2000 rows x 4 columns]